### ISSUE TITLE
Question: how to update multiple uniform variables?

### ISSUE THREAD

**Issue by shazz** [almarklein/wgpu-py#104]
Hi,

I made some good progress on my pygame-glfw-wgpu integration and I start to understand the quite chatty WebGPU dialtect. Nethertheless, the bind groups, bind groups layouts are still making me puzzled. 

I defined 4 uniforms variables in the vertex shader: `projection`, `view`, `model`, `transform`
```python
SAMPLER_BINDING = 0, 0
TEXTURE_BINDING = 0, 1
UNIFORM_BINDING = 0, 2 #not used

@python2shader
def tex_vertex_shader(
    in_pos: ("input", 0, vec4),
    in_texcoord: ("input", 1, vec2),
    out_pos: ("output", "Position", vec4),
    v_texcoord: ("output", 0, vec2),
    projection: ("uniform", (0, 2), mat4),
    view: ("uniform", (0, 3), mat4),
    model: ("uniform", (0, 4), mat4),
    transform: ("uniform", (0, 5), mat4),
):
    ndc = projection * view * model * transform * in_pos
    out_pos = vec4(ndc.xy, 0, 1)  # noqa - shader output
    v_texcoord = in_texcoord  # noqa - shader output
```

I inited them using:
```python
uniform_type = Struct(transform=mat4, projection=mat4, view=mat4, model=mat4)
uniform_data = np.asarray(shadertype_as_ctype(uniform_type)())
```

I updated them in my update loop:
```python
rot_x         = pyrr.matrix44.create_from_x_rotation(-0.3*time.time(), dtype=np.float32)
rot_y         = pyrr.matrix44.create_from_y_rotation(time.time(), dtype=np.float32)

view          = pyrr.matrix44.create_from_translation(pyrr.Vector3([0.0, 0.0, -10.0]))
projection    = pyrr.matrix44.create_perspective_projection_matrix(1200.0, aspect_ratio, 0.1, 100.0)
model         = pyrr.matrix44.create_from_translation(pyrr.Vector3([0.0, 0.0, 0.0]))

uniform_data["transform"] = (rot_x @ rot_y).flat
uniform_data["view"] = view.flat
uniform_data["projection"] = projection.flat
uniform_data["model"] = model.flat      

# instead of:
# uniform_data["transform"] = (rot_x @ rot_y @ view @ projection @ model).flat
``` 

But I did not understand yet how to initialize the pipeline:
```python
...
uniform_buffer_object = device.create_buffer(
    size=uniform_data.nbytes, 
    usage=wgpu.BufferUsage.UNIFORM | wgpu.BufferUsage.COPY_DST
uniform_buffer_object.unmap()

bind_groups_entries[0].append(
    {
        "binding": 2, #?
        "resource": {
            "buffer": uniform_buffer_object,
            "offset": 0, #?
            "size": uniform_buffer_object.size,
        },
    }
)
bind_groups_layout_entries[0].append(
    {
        "binding": 2, #?
        "visibility": wgpu.ShaderStage.VERTEX | wgpu.ShaderStage.FRAGMENT,
        "type": wgpu.BindingType.uniform_buffer,
    }
)
``` 

and update them:
```python
uniform_nbytes = uniform_data.nbytes
tmp_buffer = device.create_buffer_mapped(
    size=uniform_nbytes, usage=wgpu.BufferUsage.COPY_SRC
)
ctypes.memmove(
    ctypes.addressof(tmp_buffer.mapping), uniform_data.ctypes.data, uniform_nbytes
)
tmp_buffer.unmap()
```

Could you tell me how to complete the pipeline initialization ?

Thanks !

**Comment by almarklein** [comment]
Hi! Great to see someone using this in practice! 

> Nethertheless, the bind groups, bind groups layouts are still making me puzzled.

That only means you're human :)  I tried to explain it [here](https://wgpu-py.readthedocs.io/en/stable/reference_wgpu.html#bind-groups). Any suggestions for improving this text are very welcome indeed. I think an image would also help *a lot*.

I think the main issue in your code is that in the shader you are defining one buffer object for each matrix, while you've actually combined the matrices into one buffer object (which is good practice in general). So your shader should be more like:
```py
@python2shader
def tex_vertex_shader(
    in_pos: ("input", 0, vec4),
    in_texcoord: ("input", 1, vec2),
    out_pos: ("output", "Position", vec4),
    v_texcoord: ("output", 0, vec2),
    uni: ("uniform", (0, 2), uniform_type),   
):
    ndc = uni.projection * uni.view * uni.model * uni.transform * in_pos
    out_pos = vec4(ndc.xy, 0, 1)  # noqa - shader output
    v_texcoord = in_texcoord  # noqa - shader output
```

In other words, you have one uniform buffer object, which is a struct, that contains multiple matrices. These lines are key:
```py
uniform_type = Struct(transform=mat4, projection=mat4, view=mat4, model=mat4)
uniform_data = np.asarray(shadertype_as_ctype(uniform_type)())
```
Where the `uniform_type` is something that `python_shader` understands, so it can generate the correct SpirV. And by transforming that to a numpy struct, you have a matching data struct. (There is a step via ctypes there because we do not want to depend on numpy in `wgpu-py`.)


> Could you tell me how to complete the pipeline initialization ?

That bind group looks good. That `2` in `"binding": 2, #?` should match the `2` in ` uni: ("uniform", (0, 2), uniform_type), `.

> and update them:

In the code you showed, you upload the new data to a new buffer. Now you need to copy that buffer to the existing buffer.
```py
            command_encoder = self._device.create_command_encoder()
            command_encoder.copy_buffer_to_buffer(tmp_buffer, 0, actual_buffer, boffset, bsize)
            self._device.default_queue.submit([command_encoder.finish()])
```

This may seem a bit odd, but it seems to be the preferred way. The alternative is to map the existing buffer for writing, but this is slower.

Note that we may change the API a bit, so that creation of the tmp bufer may soon lool something like `create_buffer_from_data(...)`. See #98

**Comment by shazz** [comment]
Ah ah! Thanks, so just my shader declaration was wrong, got it. Works perfectly now!
So I have a first version of my pygame-wgpu integration, if you'd like to have a look, tell me!
